apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: test-repo
spec:
  location: us-central1
  format: DOCKER
  description: "test repository description"