apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "0" # Avoid time-dependencies
  name: storagebucket
---
apiVersion: dataflow.cnrm.cloud.google.com/v1beta1
kind: DataflowFlexTemplateJob
metadata:
  annotations:
    cnrm.cloud.google.com/on-delete: "cancel"
  name: test-job
spec:
  region: us-central1
  # This is a public, Google-maintained Dataflow Job flex template of a batch job
  containerSpecGcsPath: gs://dataflow-templates/2022-10-03-00_RC00/flex/File_Format_Conversion
  parameters:
    autoscalingAlgorithm: AUTOSCALING_ALGORITHM_NONE
    inputFileFormat: csv
    outputFileFormat: avro
    # This is maintained by us.
    inputFileSpec: gs://config-connector-samples/dataflowflextemplate/numbertest.csv
    outputBucket: gs://storagebucket
    # This is maintained by us.
    schema: gs://config-connector-samples/dataflowflextemplate/numbers.avsc